version: '3'
services:
    app:
        image: kaangiray26/store:1.0
        restart: on-failure
        ports:
            - "3000:3000"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            port: 3000 # Set Port
            NODE_ENV: production # Set Node Environment
            POSTGRES_HOST: postgres # Postgres Host/IP
            POSTGRES_USER: store # Set Postgres Username
            POSTGRES_PASSWORD: store # Set Postgres Password
            POSTGRES_DB: store # Set Postgres Database Name
        volumes:
            - uploads:/store/uploads
    postgres:
        image: kaangiray26/postgres:2.0
        restart: on-failure
        environment:
            POSTGRES_USER: store # Set Postgres Username
            POSTGRES_PASSWORD: store # Set Postgres Password
            POSTGRES_DB: store # Set Postgres Database Name
        volumes:
            - db-metadata:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U store" ]
            interval: 5s
            timeout: 5s
            retries: 5
volumes:
    db-metadata:
    uploads:
